module DateTimePicker.SharedStyles exposing (CssClasses(..))


type CssClasses
    = Calendar
    | DaysOfWeek
    | PreviousMonth
    | CurrentMonth
    | Header
    | Body
    | NextMonth
    | Days
    | Title
    | NoYearNavigation
    | ArrowLeft
    | ArrowRight
    | DoubleArrowLeft
    | DoubleArrowRight
    | ArrowUp
    | ArrowDown
    | Dialog
    | DatePickerDialog
    | TimePickerDialog
    | DatePicker
    | TimePicker
    | Footer
    | SelectedDate
    | SelectedHour
    | SelectedMinute
    | SelectedAmPm
    | DisabledDate
    | Today
    | DigitalTime
    | AnalogTime
    | AnalogClock
    | Active
    | Hour
    | Minute
    | AMPM
    | Separator
    | AMPMPicker
    | AM
    | PM
    | EmptyCell
